[program:onyx-static-publisher]
command=/opt/bizzi/bizzi/scripts/static_publisher_wrapper.sh --tenant onyx --output /opt/onyx-infos/public --loop --interval 300
directory=/opt/bizzi/bizzi
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/onyx-static-publisher.log
stderr_logfile=/var/log/onyx-static-publisher.error.log
stopasgroup=true
killasgroup=true
